services:
  mongo:
    image: mongo
    container_name: mongo-nikaro
    restart: unless-stopped
    command: --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ${MONGO_DB_DIR}:/data/db

